version: '3'
services:
  estate_postgresql:
    image: postgres
    container_name: estate_postgresql
    volumes:
      - vol_estate:/var/lib/postgresql/data
    restart: always
    env_file: .env
    ports:
      - "5432:5432"
    networks:
      - net_estate
volumes:
  vol_estate:
    external: true
networks:
  net_estate:
    external: true

